// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/relay.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage_Type int32

const (
	ControlMessage_PING         ControlMessage_Type = 0
	ControlMessage_PONG         ControlMessage_Type = 1
	ControlMessage_ACK          ControlMessage_Type = 2
	ControlMessage_TYPING_START ControlMessage_Type = 3
	ControlMessage_TYPING_STOP  ControlMessage_Type = 4
)

// Enum value maps for ControlMessage_Type.
var (
	ControlMessage_Type_name = map[int32]string{
		0: "PING",
		1: "PONG",
		2: "ACK",
		3: "TYPING_START",
		4: "TYPING_STOP",
	}
	ControlMessage_Type_value = map[string]int32{
		"PING":         0,
		"PONG":         1,
		"ACK":          2,
		"TYPING_START": 3,
		"TYPING_STOP":  4,
	}
)

func (x ControlMessage_Type) Enum() *ControlMessage_Type {
	p := new(ControlMessage_Type)
	*p = x
	return p
}

func (x ControlMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_relay_proto_enumTypes[0].Descriptor()
}

func (ControlMessage_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_relay_proto_enumTypes[0]
}

func (x ControlMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessage_Type.Descriptor instead.
func (ControlMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_relay_proto_rawDescGZIP(), []int{2, 0}
}

type RelayMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderId  string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RelayMessage_EncryptedData
	//	*RelayMessage_Control
	Payload       isRelayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessage) Reset() {
	*x = RelayMessage{}
	mi := &file_pkg_proto_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessage) ProtoMessage() {}

func (x *RelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessage.ProtoReflect.Descriptor instead.
func (*RelayMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RelayMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RelayMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RelayMessage) GetPayload() isRelayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayMessage) GetEncryptedData() *EncryptedData {
	if x != nil {
		if x, ok := x.Payload.(*RelayMessage_EncryptedData); ok {
			return x.EncryptedData
		}
	}
	return nil
}

func (x *RelayMessage) GetControl() *ControlMessage {
	if x != nil {
		if x, ok := x.Payload.(*RelayMessage_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isRelayMessage_Payload interface {
	isRelayMessage_Payload()
}

type RelayMessage_EncryptedData struct {
	EncryptedData *EncryptedData `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3,oneof"`
}

type RelayMessage_Control struct {
	Control *ControlMessage `protobuf:"bytes,5,opt,name=control,proto3,oneof"`
}

func (*RelayMessage_EncryptedData) isRelayMessage_Payload() {}

func (*RelayMessage_Control) isRelayMessage_Payload() {}

type EncryptedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Tag           []byte                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_pkg_proto_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_relay_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedData) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedData) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlMessage_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=semaclaw.relay.ControlMessage_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_pkg_proto_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMessage) GetType() ControlMessage_Type {
	if x != nil {
		return x.Type
	}
	return ControlMessage_PING
}

var File_pkg_proto_relay_proto protoreflect.FileDescriptor

const file_pkg_proto_relay_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/relay.proto\x12\x0esemaclaw.relay\"\xf7\x01\n" +
	"\fRelayMessage\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12F\n" +
	"\x0eencrypted_data\x18\x04 \x01(\v2\x1d.semaclaw.relay.EncryptedDataH\x00R\rencryptedData\x12:\n" +
	"\acontrol\x18\x05 \x01(\v2\x1e.semaclaw.relay.ControlMessageH\x00R\acontrolB\t\n" +
	"\apayload\"W\n" +
	"\rEncryptedData\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\fR\x03tag\"\x91\x01\n" +
	"\x0eControlMessage\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.semaclaw.relay.ControlMessage.TypeR\x04type\"F\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\b\n" +
	"\x04PONG\x10\x01\x12\a\n" +
	"\x03ACK\x10\x02\x12\x10\n" +
	"\fTYPING_START\x10\x03\x12\x0f\n" +
	"\vTYPING_STOP\x10\x042X\n" +
	"\fChannelRelay\x12H\n" +
	"\x06Stream\x12\x1c.semaclaw.relay.RelayMessage\x1a\x1c.semaclaw.relay.RelayMessage(\x010\x01B&Z$semaclaw/hub-backend/pkg/proto/relayb\x06proto3"

var (
	file_pkg_proto_relay_proto_rawDescOnce sync.Once
	file_pkg_proto_relay_proto_rawDescData []byte
)

func file_pkg_proto_relay_proto_rawDescGZIP() []byte {
	file_pkg_proto_relay_proto_rawDescOnce.Do(func() {
		file_pkg_proto_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_relay_proto_rawDesc), len(file_pkg_proto_relay_proto_rawDesc)))
	})
	return file_pkg_proto_relay_proto_rawDescData
}

var file_pkg_proto_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_relay_proto_goTypes = []any{
	(ControlMessage_Type)(0), // 0: semaclaw.relay.ControlMessage.Type
	(*RelayMessage)(nil),     // 1: semaclaw.relay.RelayMessage
	(*EncryptedData)(nil),    // 2: semaclaw.relay.EncryptedData
	(*ControlMessage)(nil),   // 3: semaclaw.relay.ControlMessage
}
var file_pkg_proto_relay_proto_depIdxs = []int32{
	2, // 0: semaclaw.relay.RelayMessage.encrypted_data:type_name -> semaclaw.relay.EncryptedData
	3, // 1: semaclaw.relay.RelayMessage.control:type_name -> semaclaw.relay.ControlMessage
	0, // 2: semaclaw.relay.ControlMessage.type:type_name -> semaclaw.relay.ControlMessage.Type
	1, // 3: semaclaw.relay.ChannelRelay.Stream:input_type -> semaclaw.relay.RelayMessage
	1, // 4: semaclaw.relay.ChannelRelay.Stream:output_type -> semaclaw.relay.RelayMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_relay_proto_init() }
func file_pkg_proto_relay_proto_init() {
	if File_pkg_proto_relay_proto != nil {
		return
	}
	file_pkg_proto_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*RelayMessage_EncryptedData)(nil),
		(*RelayMessage_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_relay_proto_rawDesc), len(file_pkg_proto_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_relay_proto_goTypes,
		DependencyIndexes: file_pkg_proto_relay_proto_depIdxs,
		EnumInfos:         file_pkg_proto_relay_proto_enumTypes,
		MessageInfos:      file_pkg_proto_relay_proto_msgTypes,
	}.Build()
	File_pkg_proto_relay_proto = out.File
	file_pkg_proto_relay_proto_goTypes = nil
	file_pkg_proto_relay_proto_depIdxs = nil
}
