// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/proto/relay.proto

package relay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelRelay_Stream_FullMethodName = "/semaclaw.relay.ChannelRelay/Stream"
)

// ChannelRelayClient is the client API for ChannelRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelRelayClient interface {
	// Bi-directional stream for real-time interaction
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayMessage, RelayMessage], error)
}

type channelRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelRelayClient(cc grpc.ClientConnInterface) ChannelRelayClient {
	return &channelRelayClient{cc}
}

func (c *channelRelayClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayMessage, RelayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelRelay_ServiceDesc.Streams[0], ChannelRelay_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RelayMessage, RelayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelRelay_StreamClient = grpc.BidiStreamingClient[RelayMessage, RelayMessage]

// ChannelRelayServer is the server API for ChannelRelay service.
// All implementations must embed UnimplementedChannelRelayServer
// for forward compatibility.
type ChannelRelayServer interface {
	// Bi-directional stream for real-time interaction
	Stream(grpc.BidiStreamingServer[RelayMessage, RelayMessage]) error
	mustEmbedUnimplementedChannelRelayServer()
}

// UnimplementedChannelRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelRelayServer struct{}

func (UnimplementedChannelRelayServer) Stream(grpc.BidiStreamingServer[RelayMessage, RelayMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedChannelRelayServer) mustEmbedUnimplementedChannelRelayServer() {}
func (UnimplementedChannelRelayServer) testEmbeddedByValue()                      {}

// UnsafeChannelRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelRelayServer will
// result in compilation errors.
type UnsafeChannelRelayServer interface {
	mustEmbedUnimplementedChannelRelayServer()
}

func RegisterChannelRelayServer(s grpc.ServiceRegistrar, srv ChannelRelayServer) {
	// If the following call panics, it indicates UnimplementedChannelRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelRelay_ServiceDesc, srv)
}

func _ChannelRelay_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChannelRelayServer).Stream(&grpc.GenericServerStream[RelayMessage, RelayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelRelay_StreamServer = grpc.BidiStreamingServer[RelayMessage, RelayMessage]

// ChannelRelay_ServiceDesc is the grpc.ServiceDesc for ChannelRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semaclaw.relay.ChannelRelay",
	HandlerType: (*ChannelRelayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ChannelRelay_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/relay.proto",
}
