//! MCP server (`ontology-mcp`) exposing the pipeline as tools over HTTP/SSE —
//! same JSON-RPC-over-SSE shape as the other SenClaw Space Apps. Tools are
//! `ontology_*`. They drive the exact same modules the REST API does.

use crate::api::AppState;
use crate::db::now;
use crate::{llm, mapping, prov, profile as prof, reason, resolve, shacl, tbox};
use axum::{
    extract::State,
    response::sse::{Event, Sse},
    Json,
};
use futures_util::stream::Stream;
use serde::Deserialize;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::{convert::Infallible, sync::Arc};

#[derive(Deserialize, Debug)]
pub struct JsonRpcRequest {
    #[allow(dead_code)]
    pub jsonrpc: String,
    pub id: Option<Value>,
    pub method: String,
    pub params: Option<Value>,
}

pub async fn mcp_sse(
    State(state): State<Arc<AppState>>,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    let mut rx = state.mcp_tx.subscribe();
    let stream = async_stream::stream! {
        yield Ok(Event::default().event("endpoint").data("/api/mcp/message".to_string()));
        while let Ok(msg) = rx.recv().await {
            yield Ok(Event::default().event("message").data(msg));
        }
    };
    Sse::new(stream).keep_alive(axum::response::sse::KeepAlive::default())
}

fn text(t: String) -> Value {
    json!({ "content": [{ "type": "text", "text": t }] })
}
fn jout(v: Value) -> Value {
    text(serde_json::to_string_pretty(&v).unwrap_or_default())
}
fn err(t: String) -> Value {
    json!({ "isError": true, "content": [{ "type": "text", "text": t }] })
}

pub async fn mcp_message(
    State(state): State<Arc<AppState>>,
    Json(req): Json<JsonRpcRequest>,
) -> Json<Value> {
    let reply = |result: Value| -> Json<Value> {
        let resp = json!({ "jsonrpc": "2.0", "id": req.id, "result": result });
        let _ = state.mcp_tx.send(resp.to_string());
        Json(resp)
    };
    match req.method.as_str() {
        "initialize" => reply(json!({
            "protocolVersion": "2024-11-05",
            "capabilities": { "tools": {} },
            "serverInfo": { "name": "ontology-mcp", "version": "1.0.0" }
        })),
        "ping" => reply(json!({})),
        "notifications/initialized" => Json(json!({ "jsonrpc": "2.0", "id": req.id, "result": {} })),
        "tools/list" => reply(json!({ "tools": tools_list() })),
        "tools/call" => {
            let params = req.params.clone().unwrap_or_default();
            let name = params["name"].as_str().unwrap_or("").to_string();
            let args = params["arguments"].clone();
            reply(call_tool(&state, &name, &args).await)
        }
        _ => Json(json!("ok")),
    }
}

fn obj(props: Value, required: &[&str]) -> Value {
    json!({ "type": "object", "properties": props, "required": required })
}

fn tools_list() -> Value {
    let pid = json!({ "type": "number", "description": "Project id" });
    json!([
        { "name": "ontology_list_projects", "description": "List ontology projects (id, name, triple count). Start here.", "inputSchema": obj(json!({}), &[]) },
        { "name": "ontology_create_project", "description": "Create a new ontology project. Returns its id and base IRI. Separate the schema (T-Box, designed from competency questions) from the data (A-Box, generated by mapping).", "inputSchema": obj(json!({
            "name": {"type":"string"}, "description": {"type":"string"}, "baseIri": {"type":"string"}
        }), &["name"]) },
        { "name": "ontology_add_source", "description": "Add a raw CSV or JSON-array source to a project and profile its columns (type, null ratio, uniqueness, enum, inferred role). Pass the file text as 'content'.", "inputSchema": obj(json!({
            "projectId": pid, "name": {"type":"string","description":"logical source name, e.g. products"}, "content": {"type":"string"}, "kind": {"type":"string","enum":["csv","json"]}
        }), &["projectId","name","content"]) },
        { "name": "ontology_get_tbox", "description": "Read the project's T-Box (classes + properties).", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_add_class", "description": "Add an owl:Class to the T-Box. iri may be a curie (ex:Product).", "inputSchema": obj(json!({
            "projectId": pid, "iri": {"type":"string"}, "label": {"type":"string"}, "subClassOf": {"type":"string"}
        }), &["projectId","iri"]) },
        { "name": "ontology_add_property", "description": "Add a property. kind: object|data|annotation. Set domain/range as curies. Use a data property (xsd range) for literals, an object property between classes.", "inputSchema": obj(json!({
            "projectId": pid, "iri": {"type":"string"}, "kind": {"type":"string","enum":["object","data","annotation"]}, "label": {"type":"string"}, "domain": {"type":"string"}, "range": {"type":"string"}
        }), &["projectId","iri"]) },
        { "name": "ontology_apply_tbox", "description": "Apply a full T-Box draft {prefixes,classes,properties} in one call.", "inputSchema": obj(json!({"projectId": pid, "draft": {"type":"object"}}), &["projectId","draft"]) },
        { "name": "ontology_set_mapping", "description": "Save the declarative RML-lite mapping (JSON) that turns sources into triples. Mapping is data, not code: {base,prefixes,triplesMaps:[{name,source,subject:{template|hash,class},predicateObjectMaps:[{predicate,object:{column|template|parentHash|constant, datatype?}}]}]}.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId","mapping"]) },
        { "name": "ontology_preview_mapping", "description": "Preview the triples a mapping would generate for the first rows, without writing. Pass 'mapping' to test an unsaved one, else uses the saved mapping.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_lift", "description": "Run the mapping over the full sources and materialize triples into a new provenance batch (named graph). Idempotent.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_sparql", "description": "Run a SPARQL 1.1 query over the project (default graph = union of all data + inferred).", "inputSchema": obj(json!({"projectId": pid, "query": {"type":"string"}}), &["projectId","query"]) },
        { "name": "ontology_add_competency", "description": "Save a competency question + the SPARQL that should answer it. expect: nonempty|empty|boolean.", "inputSchema": obj(json!({"projectId": pid, "question": {"type":"string"}, "sparql": {"type":"string"}, "expect": {"type":"string"}}), &["projectId","question","sparql"]) },
        { "name": "ontology_run_competency", "description": "Run all competency questions as a test suite; returns pass/fail per question.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_set_shapes", "description": "Save SHACL-lite shapes JSON {nodeShapes:[{targetClass,properties:[{path,datatype?,class?,nodeKind?,minCount?,maxCount?,minInclusive?,maxInclusive?,pattern?}]}]}.", "inputSchema": obj(json!({"projectId": pid, "shapes": {"type":"object"}}), &["projectId","shapes"]) },
        { "name": "ontology_validate", "description": "Validate the data against the saved (or supplied) SHACL-lite shapes. Returns conforms + violations.", "inputSchema": obj(json!({"projectId": pid, "shapes": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_materialize", "description": "Run RDFS/OWL-RL reasoning (subclass/subproperty/domain/range/inverse/sameAs) to a fixpoint into the inferred graph.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_resolve_candidates", "description": "Find likely-duplicate individuals of a class by label similarity (Jaro-Winkler). Returns candidate pairs to link with skos:closeMatch.", "inputSchema": obj(json!({"projectId": pid, "class": {"type":"string"}, "labelProp": {"type":"string"}, "threshold": {"type":"number"}}), &["projectId","class"]) },
        { "name": "ontology_list_batches", "description": "List provenance import batches (named graphs) with live triple counts.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_drop_batch", "description": "Drop one import batch (its named graph + PROV record) — reload a single lot without touching the rest.", "inputSchema": obj(json!({"projectId": pid, "iri": {"type":"string"}}), &["projectId","iri"]) },
        { "name": "ontology_extract", "description": "Extract RDF triples from unstructured text via the LLM (with provenance + confidence) into a dedicated batch.", "inputSchema": obj(json!({"projectId": pid, "text": {"type":"string"}}), &["projectId","text"]) }
    ])
}

macro_rules! pid {
    ($args:expr) => {
        match $args["projectId"].as_i64() {
            Some(v) => v,
            None => return err("projectId is required".into()),
        }
    };
}

async fn call_tool(state: &Arc<AppState>, name: &str, args: &Value) -> Value {
    match name {
        "ontology_list_projects" => match state.db.list_projects(&|pid| state.graph_for(pid).map(|g| g.len() as i64).unwrap_or(0)) {
            Ok(v) => jout(json!(v)),
            Err(e) => err(e.to_string()),
        },
        "ontology_create_project" => {
            let nm = args["name"].as_str().unwrap_or("").trim();
            if nm.is_empty() {
                return err("name is required".into());
            }
            let base = args["baseIri"].as_str().filter(|s| !s.trim().is_empty()).map(String::from)
                .unwrap_or_else(|| format!("http://senclaw.local/onto/{}/", crate::vocab::encode_segment(nm)));
            match state.db.create_project(nm, args["description"].as_str().unwrap_or(""), &base) {
                Ok(id) => {
                    let ex = format!("{}#", base.trim_end_matches(['/', '#']));
                    let _ = state.db.set_prefixes(id, &json!({ "ex": ex }));
                    jout(json!({ "id": id, "baseIri": base }))
                }
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_source" => {
            let id = pid!(args);
            let nm = args["name"].as_str().unwrap_or("").trim();
            let content = args["content"].as_str().unwrap_or("");
            if nm.is_empty() || content.is_empty() {
                return err("name and content are required".into());
            }
            let kind = args["kind"].as_str().unwrap_or(if nm.ends_with(".json") { "json" } else { "csv" });
            match prof::parse(kind, content) {
                Ok(t) => {
                    let cols = json!(prof::profile(&t));
                    match state.db.add_source(id, nm, kind, content, &cols, t.rows.len() as i64) {
                        Ok(sid) => jout(json!({ "sourceId": sid, "rowCount": t.rows.len(), "columns": cols })),
                        Err(e) => err(e.to_string()),
                    }
                }
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_get_tbox" => {
            let id = pid!(args);
            match state.graph_for(id).and_then(|g| tbox::read(&g)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_class" => {
            let id = pid!(args);
            run_tbox(state, id, args, true).await
        }
        "ontology_add_property" => {
            let id = pid!(args);
            run_tbox(state, id, args, false).await
        }
        "ontology_apply_tbox" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
            let draft: tbox::TboxDraft = match serde_json::from_value(args["draft"].clone()) {
                Ok(d) => d, Err(e) => return err(format!("invalid draft: {e}")),
            };
            let g = match state.graph_for(id) { Ok(g) => g, Err(e) => return err(e.to_string()) };
            match tbox::apply_draft(&g, &base, &pfx, &draft) {
                Ok((nc, np)) => {
                    if !draft.prefixes.is_empty() {
                        let mut m = pfx.clone(); m.extend(draft.prefixes.clone());
                        let _ = state.db.set_prefixes(id, &json!(m));
                    }
                    let _ = state.persist(id, &g);
                    jout(json!({ "classes": nc, "properties": np }))
                }
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_set_mapping" => {
            let id = pid!(args);
            let m = args["mapping"].clone();
            if serde_json::from_value::<mapping::Mapping>(m.clone()).is_err() {
                return err("invalid mapping DSL".into());
            }
            match state.db.set_mapping(id, &m) {
                Ok(()) => jout(json!({ "ok": true })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_preview_mapping" | "ontology_lift" => {
            let id = pid!(args);
            run_lift(state, id, args, name == "ontology_lift").await
        }
        "ontology_sparql" => {
            let id = pid!(args);
            let q = args["query"].as_str().unwrap_or("");
            let pfx = state.ctx(id).map(|(_, p)| p).unwrap_or_default();
            match state.graph_for(id).and_then(|g| g.query_json(&crate::vocab::ensure_prefixes(q, &pfx))) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_competency" => {
            let id = pid!(args);
            match state.db.add_cq(id, args["question"].as_str().unwrap_or(""), args["sparql"].as_str().unwrap_or(""), args["expect"].as_str().unwrap_or("nonempty")) {
                Ok(cid) => jout(json!({ "id": cid })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_run_competency" => {
            let id = pid!(args);
            run_competency(state, id)
        }
        "ontology_set_shapes" => {
            let id = pid!(args);
            let sh = args["shapes"].clone();
            if serde_json::from_value::<shacl::Shapes>(sh.clone()).is_err() {
                return err("invalid shapes".into());
            }
            match state.db.set_shapes(id, &sh) {
                Ok(()) => jout(json!({ "ok": true })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_validate" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
            let raw = if args["shapes"].is_object() { args["shapes"].clone() } else { state.db.get_shapes(id).unwrap_or(json!({"nodeShapes":[]})) };
            let shapes: shacl::Shapes = match serde_json::from_value(raw) { Ok(s) => s, Err(e) => return err(e.to_string()) };
            match state.graph_for(id).and_then(|g| shacl::validate(&g, &base, &pfx, &shapes)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_materialize" => {
            let id = pid!(args);
            match state.graph_for(id) {
                Ok(g) => match reason::materialize(&g) {
                    Ok(rep) => { let _ = state.persist(id, &g); jout(rep) }
                    Err(e) => err(e.to_string()),
                },
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_resolve_candidates" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
            let class = args["class"].as_str().unwrap_or("");
            let lp = args["labelProp"].as_str().unwrap_or("rdfs:label");
            let th = args["threshold"].as_f64().unwrap_or(0.9);
            match state.graph_for(id).and_then(|g| resolve::candidates(&g, &base, &pfx, class, lp, th)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_list_batches" => {
            let id = pid!(args);
            match state.graph_for(id).and_then(|g| prov::list_batches(&g)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_drop_batch" => {
            let id = pid!(args);
            let iri = args["iri"].as_str().unwrap_or("");
            match state.graph_for(id) {
                Ok(g) => match prov::drop_batch(&g, iri) {
                    Ok(()) => { let _ = state.persist(id, &g); jout(json!({ "ok": true })) }
                    Err(e) => err(e.to_string()),
                },
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_extract" => {
            let id = pid!(args);
            run_extract(state, id, args).await
        }
        _ => err(format!("Unknown tool: {name}")),
    }
}

async fn run_tbox(state: &Arc<AppState>, id: i64, args: &Value, is_class: bool) -> Value {
    let (base, pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
    let g = match state.graph_for(id) { Ok(g) => g, Err(e) => return err(e.to_string()) };
    let res = if is_class {
        serde_json::from_value::<tbox::ClassDef>(args.clone()).map_err(|e| e.to_string())
            .and_then(|d| tbox::add_class(&g, &base, &pfx, &d).map_err(|e| e.to_string()))
    } else {
        serde_json::from_value::<tbox::PropertyDef>(args.clone()).map_err(|e| e.to_string())
            .and_then(|d| tbox::add_property(&g, &base, &pfx, &d).map_err(|e| e.to_string()))
    };
    match res {
        Ok(iri) => { let _ = state.persist(id, &g); jout(json!({ "iri": iri })) }
        Err(e) => err(e),
    }
}

async fn run_lift(state: &Arc<AppState>, id: i64, args: &Value, write: bool) -> Value {
    let (base, _pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
    let raw = if args["mapping"].is_object() { args["mapping"].clone() } else { state.db.get_mapping(id).unwrap_or(json!({})) };
    let m: mapping::Mapping = match serde_json::from_value(raw) { Ok(m) => m, Err(e) => return err(format!("invalid mapping: {e}")) };
    // Resolve sources.
    let mut sources: HashMap<String, prof::Table> = HashMap::new();
    for tm in &m.triples_maps {
        if sources.contains_key(&tm.source) { continue; }
        match state.db.source_by_name(id, &tm.source) {
            Ok(Some((kind, content))) => match prof::parse(&kind, &content) {
                Ok(t) => { sources.insert(tm.source.clone(), t); }
                Err(e) => return err(e.to_string()),
            },
            _ => return err(format!("source '{}' not uploaded", tm.source)),
        }
    }
    let g = match state.graph_for(id) { Ok(g) => g, Err(e) => return err(e.to_string()) };
    if write {
        let ts = now();
        let label = m.triples_maps.first().map(|t| t.source.clone()).unwrap_or_else(|| "import".into());
        let batch = prov::batch_iri(ts, &label);
        match mapping::lift(&g, &m, &sources, &base, &batch) {
            Ok(rep) => {
                let _ = prov::record_batch(&g, &batch, &label, &label, "lift", rep.triples, ts);
                let _ = state.persist(id, &g);
                jout(json!({ "batch": batch, "triples": rep.triples, "subjects": rep.subjects, "skippedRows": rep.skipped_rows, "totalTriples": g.len() }))
            }
            Err(e) => err(e.to_string()),
        }
    } else {
        match mapping::preview(&m, &sources, &base, 25) {
            Ok(rep) => jout(json!({
                "triples": rep.triples, "subjects": rep.subjects, "skippedRows": rep.skipped_rows,
                "samples": rep.samples.iter().map(|(a,b,c)| json!([a,b,c])).collect::<Vec<_>>(),
            })),
            Err(e) => err(e.to_string()),
        }
    }
}

fn run_competency(state: &Arc<AppState>, id: i64) -> Value {
    let g = match state.graph_for(id) { Ok(g) => g, Err(e) => return err(e.to_string()) };
    let pfx = state.ctx(id).map(|(_, p)| p).unwrap_or_default();
    let cqs = match state.db.list_cq(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
    let mut results = Vec::new();
    let mut passed = 0;
    for cq in &cqs {
        if cq.sparql.trim().is_empty() {
            results.push(json!({ "question": cq.question, "pass": false, "error": "no SPARQL" }));
            continue;
        }
        match g.query_json(&crate::vocab::ensure_prefixes(&cq.sparql, &pfx)) {
            Ok(res) => {
                let count = res["rows"].as_array().map(|a| a.len()).unwrap_or(0);
                let pass = match cq.expect.as_str() {
                    "empty" => count == 0,
                    "boolean" => res["boolean"].as_bool().unwrap_or(false),
                    _ => count > 0 || res["boolean"].as_bool().unwrap_or(false),
                };
                if pass { passed += 1; }
                results.push(json!({ "question": cq.question, "pass": pass, "count": count }));
            }
            Err(e) => results.push(json!({ "question": cq.question, "pass": false, "error": e.to_string() })),
        }
    }
    jout(json!({ "total": cqs.len(), "passed": passed, "results": results }))
}

async fn run_extract(state: &Arc<AppState>, id: i64, args: &Value) -> Value {
    let (base, pfx) = match state.ctx(id) { Ok(v) => v, Err(e) => return err(e.to_string()) };
    let txt = args["text"].as_str().unwrap_or("");
    if txt.trim().is_empty() {
        return err("text is required".into());
    }
    let g = match state.graph_for(id) { Ok(g) => g, Err(e) => return err(e.to_string()) };
    let tb = tbox::read(&g).unwrap_or(json!({}));
    let (extracted, model) = match llm::extract_triples(txt, &tb).await {
        Ok(v) => v, Err(e) => return err(e),
    };
    let ts = now();
    let batch = prov::batch_iri(ts, "text-extract");
    let mut body = String::new();
    let mut inserted = 0;
    if let Some(arr) = extracted["triples"].as_array() {
        for t in arr {
            let (s_raw, p_raw, o_raw) = (t["s"].as_str().unwrap_or(""), t["p"].as_str().unwrap_or(""), t["o"].as_str().unwrap_or(""));
            if s_raw.is_empty() || p_raw.is_empty() || o_raw.is_empty() { continue; }
            let subj = mint(s_raw, &base, &pfx);
            let pred = crate::vocab::expand(p_raw, &pfx, &base);
            let (Some(st), Some(pt)) = (crate::vocab::iri_term(&subj), crate::vocab::iri_term(&pred)) else { continue };
            let obj = if t["oIsLiteral"].as_bool().unwrap_or(true) {
                format!("\"{}\"", crate::vocab::escape_literal(o_raw))
            } else {
                match crate::vocab::iri_term(&mint(o_raw, &base, &pfx)) { Some(x) => x, None => continue }
            };
            body.push_str(&format!("{st} {pt} {obj} .\n"));
            inserted += 1;
        }
    }
    if inserted > 0 {
        if g.update(&format!("INSERT DATA {{ GRAPH <{batch}> {{\n{body}}} }}")).is_ok() {
            let _ = prov::record_batch(&g, &batch, "text extraction", "unstructured text (LLM)", "extract", inserted, ts);
            let _ = state.persist(id, &g);
        }
    }
    jout(json!({ "inserted": inserted, "model": model, "batch": batch }))
}

fn mint(raw: &str, base: &str, pfx: &HashMap<String, String>) -> String {
    let r = raw.trim();
    if r.starts_with("http://") || r.starts_with("https://") || r.starts_with("urn:") || r.contains(':') {
        crate::vocab::expand(r, pfx, base)
    } else {
        crate::vocab::hashed_iri(base, "entity", &[r])
    }
}
