//! MCP server (`ontology-mcp`) exposing the pipeline as tools over HTTP/SSE —
//! same JSON-RPC-over-SSE shape as the other SenClaw Space Apps. Tools are
//! `ontology_*`. They drive the exact same modules the REST API does.

use crate::api::AppState;
use crate::db::now;
use crate::{llm, mapping, profile as prof, prov, reason, resolve, shacl, tbox};
use axum::{
    extract::State,
    response::sse::{Event, Sse},
    Json,
};
use futures_util::stream::Stream;
use serde::Deserialize;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::{convert::Infallible, sync::Arc};

#[derive(Deserialize, Debug)]
pub struct JsonRpcRequest {
    #[allow(dead_code)]
    pub jsonrpc: String,
    pub id: Option<Value>,
    pub method: String,
    pub params: Option<Value>,
}

pub async fn mcp_sse(
    State(state): State<Arc<AppState>>,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    let mut rx = state.mcp_tx.subscribe();
    let stream = async_stream::stream! {
        yield Ok(Event::default().event("endpoint").data("/api/mcp/message".to_string()));
        while let Ok(msg) = rx.recv().await {
            yield Ok(Event::default().event("message").data(msg));
        }
    };
    Sse::new(stream).keep_alive(axum::response::sse::KeepAlive::default())
}

fn text(t: String) -> Value {
    json!({ "content": [{ "type": "text", "text": t }] })
}
fn jout(v: Value) -> Value {
    text(serde_json::to_string_pretty(&v).unwrap_or_default())
}
fn err(t: String) -> Value {
    json!({ "isError": true, "content": [{ "type": "text", "text": t }] })
}

pub async fn mcp_message(
    State(state): State<Arc<AppState>>,
    Json(req): Json<JsonRpcRequest>,
) -> Json<Value> {
    let reply = |result: Value| -> Json<Value> {
        let resp = json!({ "jsonrpc": "2.0", "id": req.id, "result": result });
        let _ = state.mcp_tx.send(resp.to_string());
        Json(resp)
    };
    match req.method.as_str() {
        "initialize" => reply(json!({
            "protocolVersion": "2024-11-05",
            "capabilities": { "tools": {} },
            "serverInfo": { "name": "ontology-mcp", "version": "1.0.0" }
        })),
        "ping" => reply(json!({})),
        "notifications/initialized" => {
            Json(json!({ "jsonrpc": "2.0", "id": req.id, "result": {} }))
        }
        "tools/list" => reply(json!({ "tools": tools_list() })),
        "tools/call" => {
            let params = req.params.clone().unwrap_or_default();
            let name = params["name"].as_str().unwrap_or("").to_string();
            let args = params["arguments"].clone();
            reply(call_tool(&state, &name, &args).await)
        }
        _ => Json(json!("ok")),
    }
}

fn obj(props: Value, required: &[&str]) -> Value {
    json!({ "type": "object", "properties": props, "required": required })
}

fn tools_list() -> Value {
    let pid = json!({ "type": "number", "description": "Project id" });
    json!([
        { "name": "ontology_list_projects", "description": "List ontology projects (id, name, triple count). Start here.", "inputSchema": obj(json!({}), &[]) },
        { "name": "ontology_create_project", "description": "Create a new ontology project. Returns its id and base IRI. Separate the schema (T-Box, designed from competency questions) from the data (A-Box, generated by mapping).", "inputSchema": obj(json!({
            "name": {"type":"string"}, "description": {"type":"string"}, "baseIri": {"type":"string"}
        }), &["name"]) },
        { "name": "ontology_ingest", "description": "THE EASY PATH for loading data. Paste the raw text of ANY file — CSV, TSV, JSON (nested or wrapped), JSON Lines, YAML, XML, Markdown table, HTML, or plain prose — and it is auto-detected, flattened into a table (or kept as text for AI extraction) and profiled. One upload may create several sources. Do not pre-convert anything; do not set 'kind' unless you must force it.", "inputSchema": obj(json!({
            "projectId": pid, "name": {"type":"string","description":"logical source name / filename, e.g. products.csv"}, "content": {"type":"string","description":"the raw file text"}, "kind": {"type":"string","enum":["csv","json","text"],"description":"optional override; omit to auto-detect"}
        }), &["projectId","name","content"]) },
        { "name": "ontology_autobuild", "description": "ONE CALL BUILDS THE WHOLE GRAPH. Runs the full pipeline over every source already in the project: profile -> draft competency questions -> design the T-Box -> author & mechanically repair the mapping -> lift rows -> extract triples from text sources -> draft SHACL shapes & validate -> write SPARQL for each competency question and run the suite -> materialize inferences. Returns a jobId immediately; poll ontology_autobuild_status. Use this instead of calling the individual stages unless the user wants manual control.", "inputSchema": obj(json!({
            "projectId": pid, "reason": {"type":"boolean","description":"run RDFS/OWL-RL materialization (default true)"}, "extract": {"type":"boolean","description":"run LLM extraction over text sources (default true)"}, "maxChunks": {"type":"number","description":"cap on extraction chunks per text document (default 12)"}
        }), &["projectId"]) },
        { "name": "ontology_autobuild_status", "description": "Poll an autobuild job: per-step status (pending/running/ok/warn/error/skipped) plus the final result (triple count, competency pass ratio, validation report, mapping repairs).", "inputSchema": obj(json!({"jobId": {"type":"string"}}), &["jobId"]) },
        { "name": "ontology_ask", "description": "ASK IN PLAIN LANGUAGE. Translates the question to SPARQL grounded on the classes/predicates the data really uses, runs it (self-repairing once if it fails or matches nothing), and returns a natural-language answer together with the query and the rows so it stays checkable. Prefer this over ontology_sparql when the user asked a question rather than for a query.", "inputSchema": obj(json!({"projectId": pid, "question": {"type":"string"}}), &["projectId","question"]) },
        { "name": "ontology_assist", "description": "AIP ASSIST — ask about the PLATFORM or about the project's METADATA: how a stage works, which columns a source has, what a class or property means, how the mapping is wired, which constraints apply, where a batch of triples came from. It is context-aware: pass the tab the user is looking at (studio|sources|tbox|mapping|explore|competency|validate|governance) and the source they have open, and the same question gets a different, better-targeted answer. Returns an answer with numbered citations. IMPORTANT: it indexes metadata only — no cell values, samples or literals — so it CANNOT tell you what the data says. For counts, totals or values use ontology_ask instead; assist will say so itself.", "inputSchema": obj(json!({
            "projectId": pid, "question": {"type":"string"}, "context": {"type":"object","description":"session context, e.g. {\"tab\":\"mapping\",\"source\":\"products\"}","properties":{"tab":{"type":"string"},"source":{"type":"string"},"selection":{"type":"string"}}}
        }), &["projectId","question"]) },
        { "name": "ontology_create_function", "description": "AIP LOGIC — create a function that emits TYPED ACTIONS as reviewable proposals, never a direct write. kind 'extract' pulls facts from text sources; 'classify' runs the instruction over each row of a source ('target' = source name); 'resolve' finds duplicate individuals of a class by label similarity ('target' = class, e.g. ex:Supplier — no LLM, deterministic) and proposes skos:closeMatch links. 'instruction' is the plain-language task (for resolve, may include a threshold like 0.9 or 90%). autoApply=false (default) queues proposals for human approval; true applies valid ones immediately (still audited). Every action is type-checked against the T-Box, so a hallucinated class/property is rejected at proposal time.", "inputSchema": obj(json!({
            "projectId": pid, "name": {"type":"string"}, "kind": {"type":"string","enum":["extract","classify","resolve"]}, "target": {"type":"string","description":"source name (classify) · class curie (resolve) · optional text source (extract)"}, "instruction": {"type":"string"}, "autoApply": {"type":"boolean"}
        }), &["projectId","name","instruction"]) },
        { "name": "ontology_list_functions", "description": "List AIP Logic functions and the proposal-queue counts by status.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_trial_function", "description": "Trial-run a function on a small sample WITHOUT writing anything — preview the typed actions it would propose (with validity, rationale, confidence). Do this before a full run.", "inputSchema": obj(json!({"projectId": pid, "functionId": {"type":"number"}}), &["projectId","functionId"]) },
        { "name": "ontology_run_function", "description": "Run a function over its whole input. Emits validated proposals into the queue (or applies them if the function is autoApply). Returns proposed/invalid/applied counts.", "inputSchema": obj(json!({"projectId": pid, "functionId": {"type":"number"}}), &["projectId","functionId"]) },
        { "name": "ontology_list_proposals", "description": "The proposal queue: each pending typed action with its summary, rationale, confidence, and whether it passed the type checker. Optional status filter (pending|approved|rejected|invalid).", "inputSchema": obj(json!({"projectId": pid, "status": {"type":"string"}}), &["projectId"]) },
        { "name": "ontology_approve_proposals", "description": "Approve proposals (empty ids = all pending valid ones) — re-validates against the current T-Box and applies them as ONE provenance batch you can later drop. This is the only path from an LLM proposal to actual data.", "inputSchema": obj(json!({"projectId": pid, "ids": {"type":"array","items":{"type":"number"}}}), &["projectId"]) },
        { "name": "ontology_reject_proposals", "description": "Reject proposals (empty ids = all pending). They are marked rejected and never applied.", "inputSchema": obj(json!({"projectId": pid, "ids": {"type":"array","items":{"type":"number"}}}), &["projectId"]) },
        { "name": "ontology_live_schema", "description": "The classes and predicates that actually occur in the data, with counts and a sample value — what to ground a hand-written SPARQL query on (the T-Box says what should exist; this says what does).", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_add_source", "description": "Lower-level source add when you already know the format. Prefer ontology_ingest. Pass the file text as 'content' and kind csv|json|text.", "inputSchema": obj(json!({
            "projectId": pid, "name": {"type":"string","description":"logical source name, e.g. products"}, "content": {"type":"string"}, "kind": {"type":"string","enum":["csv","json","text"]}
        }), &["projectId","name","content"]) },
        { "name": "ontology_get_tbox", "description": "Read the project's T-Box (classes + properties).", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_add_class", "description": "Add an owl:Class to the T-Box. iri may be a curie (ex:Product).", "inputSchema": obj(json!({
            "projectId": pid, "iri": {"type":"string"}, "label": {"type":"string"}, "subClassOf": {"type":"string"}
        }), &["projectId","iri"]) },
        { "name": "ontology_add_property", "description": "Add a property. kind: object|data|annotation. Set domain/range as curies. Use a data property (xsd range) for literals, an object property between classes.", "inputSchema": obj(json!({
            "projectId": pid, "iri": {"type":"string"}, "kind": {"type":"string","enum":["object","data","annotation"]}, "label": {"type":"string"}, "domain": {"type":"string"}, "range": {"type":"string"}
        }), &["projectId","iri"]) },
        { "name": "ontology_apply_tbox", "description": "Apply a full T-Box draft {prefixes,classes,properties} in one call.", "inputSchema": obj(json!({"projectId": pid, "draft": {"type":"object"}}), &["projectId","draft"]) },
        { "name": "ontology_set_mapping", "description": "Save the declarative RML-lite mapping (JSON) that turns sources into triples. Mapping is data, not code: {base,prefixes,triplesMaps:[{name,source,subject:{template|hash,class},predicateObjectMaps:[{predicate,object:{column|template|parentHash|constant, datatype?}}]}]}.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId","mapping"]) },
        { "name": "ontology_preview_mapping", "description": "Preview the triples a mapping would generate for the first rows, without writing. Pass 'mapping' to test an unsaved one, else uses the saved mapping.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_lift", "description": "Run the mapping over the full sources and materialize triples into a new provenance batch (named graph). Idempotent.", "inputSchema": obj(json!({"projectId": pid, "mapping": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_sparql", "description": "Run a SPARQL 1.1 query over the project (default graph = union of all data + inferred).", "inputSchema": obj(json!({"projectId": pid, "query": {"type":"string"}}), &["projectId","query"]) },
        { "name": "ontology_add_competency", "description": "Save a competency question + the SPARQL that should answer it. expect: nonempty|empty|boolean.", "inputSchema": obj(json!({"projectId": pid, "question": {"type":"string"}, "sparql": {"type":"string"}, "expect": {"type":"string"}}), &["projectId","question","sparql"]) },
        { "name": "ontology_run_competency", "description": "Run all competency questions as a test suite; returns pass/fail per question.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_set_shapes", "description": "Save SHACL-lite shapes JSON {nodeShapes:[{targetClass,properties:[{path,datatype?,class?,nodeKind?,minCount?,maxCount?,minInclusive?,maxInclusive?,pattern?}]}]}.", "inputSchema": obj(json!({"projectId": pid, "shapes": {"type":"object"}}), &["projectId","shapes"]) },
        { "name": "ontology_validate", "description": "Validate the data against the saved (or supplied) SHACL-lite shapes. Returns conforms + violations.", "inputSchema": obj(json!({"projectId": pid, "shapes": {"type":"object"}}), &["projectId"]) },
        { "name": "ontology_materialize", "description": "Run RDFS/OWL-RL reasoning (subclass/subproperty/domain/range/inverse/sameAs) to a fixpoint into the inferred graph.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_resolve_candidates", "description": "Find likely-duplicate individuals of a class by label similarity (Jaro-Winkler). Returns candidate pairs to link with skos:closeMatch.", "inputSchema": obj(json!({"projectId": pid, "class": {"type":"string"}, "labelProp": {"type":"string"}, "threshold": {"type":"number"}}), &["projectId","class"]) },
        { "name": "ontology_list_batches", "description": "List provenance import batches (named graphs) with live triple counts.", "inputSchema": obj(json!({"projectId": pid}), &["projectId"]) },
        { "name": "ontology_drop_batch", "description": "Drop one import batch (its named graph + PROV record) — reload a single lot without touching the rest.", "inputSchema": obj(json!({"projectId": pid, "iri": {"type":"string"}}), &["projectId","iri"]) },
        { "name": "ontology_extract", "description": "Extract RDF triples from unstructured text via the LLM (with provenance + confidence) into a dedicated batch. Long documents are chunked automatically — pass the whole text, do not pre-split it.", "inputSchema": obj(json!({"projectId": pid, "text": {"type":"string"}, "label": {"type":"string","description":"what this document is, for provenance"}, "maxChunks": {"type":"number","description":"cost cap, default 12"}}), &["projectId","text"]) }
    ])
}

macro_rules! pid {
    ($args:expr) => {
        match $args["projectId"].as_i64() {
            Some(v) => v,
            None => return err("projectId is required".into()),
        }
    };
}

async fn call_tool(state: &Arc<AppState>, name: &str, args: &Value) -> Value {
    match name {
        "ontology_list_projects" => match state
            .db
            .list_projects(&|pid| state.graph_for(pid).map(|g| g.len() as i64).unwrap_or(0))
        {
            Ok(v) => jout(json!(v)),
            Err(e) => err(e.to_string()),
        },
        "ontology_create_project" => {
            let nm = args["name"].as_str().unwrap_or("").trim();
            if nm.is_empty() {
                return err("name is required".into());
            }
            let base = args["baseIri"]
                .as_str()
                .filter(|s| !s.trim().is_empty())
                .map(String::from)
                .unwrap_or_else(|| {
                    format!(
                        "http://senclaw.local/onto/{}/",
                        crate::vocab::encode_segment(nm)
                    )
                });
            match state
                .db
                .create_project(nm, args["description"].as_str().unwrap_or(""), &base)
            {
                Ok(id) => {
                    let ex = format!("{}#", base.trim_end_matches(['/', '#']));
                    let _ = state.db.set_prefixes(id, &json!({ "ex": ex }));
                    jout(json!({ "id": id, "baseIri": base }))
                }
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_source" | "ontology_ingest" => {
            let id = pid!(args);
            let nm = args["name"].as_str().unwrap_or("").trim();
            let content = args["content"].as_str().unwrap_or("");
            if nm.is_empty() || content.is_empty() {
                return err("name and content are required".into());
            }
            // An explicit kind short-circuits detection; otherwise the sniffer
            // decides, so pasting YAML/XML/JSONL/Markdown still works.
            let parts = match args["kind"].as_str().filter(|k| !k.trim().is_empty()) {
                Some(kind) => vec![crate::ingest::Ingested {
                    name: nm.to_string(),
                    kind: kind.to_string(),
                    origin: kind.to_string(),
                    content: content.to_string(),
                    note: String::new(),
                    rows: 0,
                    columns: 0,
                }],
                None => match crate::ingest::ingest_text(nm, content) {
                    Ok(v) => v,
                    Err(e) => return err(e.to_string()),
                },
            };
            let mut out = Vec::new();
            for p in parts {
                let t = match prof::parse(&p.kind, &p.content) {
                    Ok(t) => t,
                    Err(e) => return err(e.to_string()),
                };
                let cols = json!(prof::profile(&t));
                match state.db.add_source(
                    id,
                    &p.name,
                    &p.kind,
                    &p.content,
                    &cols,
                    t.rows.len() as i64,
                    &p.origin,
                    &p.note,
                ) {
                    Ok(sid) => out.push(json!({
                        "sourceId": sid, "name": p.name, "kind": p.kind, "origin": p.origin,
                        "note": p.note, "rowCount": t.rows.len(), "columns": cols
                    })),
                    Err(e) => return err(e.to_string()),
                }
            }
            jout(json!({ "sources": out }))
        }
        "ontology_autobuild" => {
            let id = pid!(args);
            let opts: crate::auto::AutoOpts =
                serde_json::from_value(args.clone()).unwrap_or_default();
            let job = crate::auto::start(state.clone(), id, opts);
            jout(json!({
                "jobId": job,
                "note": "Autobuild is running in the background. Poll ontology_autobuild_status with this jobId."
            }))
        }
        "ontology_autobuild_status" => {
            let job = args["jobId"].as_str().unwrap_or("");
            let handle = state.jobs.lock().unwrap().get(job).cloned();
            match handle {
                Some(h) => {
                    let snap = h.lock().unwrap().clone();
                    match serde_json::to_value(snap) {
                        Ok(v) => jout(v),
                        Err(e) => err(e.to_string()),
                    }
                }
                None => err(format!("no such job: {job}")),
            }
        }
        "ontology_ask" => {
            let id = pid!(args);
            match crate::auto::ask(state, id, args["question"].as_str().unwrap_or("")).await {
                Ok(v) => jout(v),
                Err(e) => err(e),
            }
        }
        "ontology_create_function" => {
            let id = pid!(args);
            let name = args["name"].as_str().unwrap_or("").trim();
            if name.is_empty() {
                return err("name is required".into());
            }
            let kind = match args["kind"].as_str() {
                Some("classify") => "classify",
                Some("resolve") => "resolve",
                _ => "extract",
            };
            let input_kind = match kind {
                "classify" => "source",
                "resolve" => "class",
                _ => "text",
            };
            match state.db.create_function(
                id,
                name,
                kind,
                input_kind,
                args["target"].as_str().unwrap_or(""),
                args["instruction"].as_str().unwrap_or(""),
                args["autoApply"].as_bool().unwrap_or(false),
            ) {
                Ok(fid) => jout(json!({ "functionId": fid, "kind": kind })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_list_functions" => {
            let id = pid!(args);
            match (state.db.list_functions(id), state.db.proposal_counts(id)) {
                (Ok(f), Ok(c)) => jout(json!({ "functions": f, "proposalCounts": c })),
                (Err(e), _) | (_, Err(e)) => err(e.to_string()),
            }
        }
        "ontology_run_function" | "ontology_trial_function" => {
            let id = pid!(args);
            let Some(fid) = args["functionId"].as_i64() else {
                return err("functionId is required".into());
            };
            let trial = name == "ontology_trial_function";
            match crate::logic::run(state, id, fid, trial).await {
                Ok(rep) => jout(serde_json::to_value(rep).unwrap_or_default()),
                Err(e) => err(e),
            }
        }
        "ontology_list_proposals" => {
            let id = pid!(args);
            let status = args["status"].as_str();
            match (
                state.db.list_proposals(id, status),
                state.db.proposal_counts(id),
            ) {
                (Ok(p), Ok(c)) => jout(json!({ "proposals": p, "counts": c })),
                (Err(e), _) | (_, Err(e)) => err(e.to_string()),
            }
        }
        "ontology_approve_proposals" => {
            let id = pid!(args);
            let ids: Vec<i64> = args["ids"]
                .as_array()
                .map(|a| a.iter().filter_map(|x| x.as_i64()).collect())
                .unwrap_or_default();
            match crate::logic::approve(state, id, &ids).await {
                Ok(v) => jout(v),
                Err(e) => err(e),
            }
        }
        "ontology_reject_proposals" => {
            let id = pid!(args);
            let ids: Vec<i64> = args["ids"]
                .as_array()
                .map(|a| a.iter().filter_map(|x| x.as_i64()).collect())
                .unwrap_or_default();
            match state.db.reject_proposals(id, &ids) {
                Ok(n) => jout(json!({ "rejected": n })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_assist" => {
            let id = pid!(args);
            let ctx: crate::aip::Context =
                serde_json::from_value(args["context"].clone()).unwrap_or_default();
            match crate::aip::assist(state, id, args["question"].as_str().unwrap_or(""), &ctx).await
            {
                Ok(v) => jout(v),
                Err(e) => err(e),
            }
        }
        "ontology_live_schema" => {
            let id = pid!(args);
            match state.graph_for(id).and_then(|g| tbox::live_schema(&g)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_get_tbox" => {
            let id = pid!(args);
            match state.graph_for(id).and_then(|g| tbox::read(&g)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_class" => {
            let id = pid!(args);
            run_tbox(state, id, args, true).await
        }
        "ontology_add_property" => {
            let id = pid!(args);
            run_tbox(state, id, args, false).await
        }
        "ontology_apply_tbox" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) {
                Ok(v) => v,
                Err(e) => return err(e.to_string()),
            };
            let draft: tbox::TboxDraft = match serde_json::from_value(args["draft"].clone()) {
                Ok(d) => d,
                Err(e) => return err(format!("invalid draft: {e}")),
            };
            let g = match state.graph_for(id) {
                Ok(g) => g,
                Err(e) => return err(e.to_string()),
            };
            match tbox::apply_draft(&g, &base, &pfx, &draft) {
                Ok((nc, np)) => {
                    if !draft.prefixes.is_empty() {
                        let mut m = pfx.clone();
                        m.extend(draft.prefixes.clone());
                        let _ = state.db.set_prefixes(id, &json!(m));
                    }
                    let _ = state.persist(id, &g);
                    jout(json!({ "classes": nc, "properties": np }))
                }
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_set_mapping" => {
            let id = pid!(args);
            let m = args["mapping"].clone();
            if serde_json::from_value::<mapping::Mapping>(m.clone()).is_err() {
                return err("invalid mapping DSL".into());
            }
            match state.db.set_mapping(id, &m) {
                Ok(()) => jout(json!({ "ok": true })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_preview_mapping" | "ontology_lift" => {
            let id = pid!(args);
            run_lift(state, id, args, name == "ontology_lift").await
        }
        "ontology_sparql" => {
            let id = pid!(args);
            let q = args["query"].as_str().unwrap_or("");
            let pfx = state.ctx(id).map(|(_, p)| p).unwrap_or_default();
            match state
                .graph_for(id)
                .and_then(|g| g.query_json(&crate::vocab::ensure_prefixes(q, &pfx)))
            {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_add_competency" => {
            let id = pid!(args);
            match state.db.add_cq(
                id,
                args["question"].as_str().unwrap_or(""),
                args["sparql"].as_str().unwrap_or(""),
                args["expect"].as_str().unwrap_or("nonempty"),
            ) {
                Ok(cid) => jout(json!({ "id": cid })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_run_competency" => {
            let id = pid!(args);
            run_competency(state, id)
        }
        "ontology_set_shapes" => {
            let id = pid!(args);
            let sh = args["shapes"].clone();
            if serde_json::from_value::<shacl::Shapes>(sh.clone()).is_err() {
                return err("invalid shapes".into());
            }
            match state.db.set_shapes(id, &sh) {
                Ok(()) => jout(json!({ "ok": true })),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_validate" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) {
                Ok(v) => v,
                Err(e) => return err(e.to_string()),
            };
            let raw = if args["shapes"].is_object() {
                args["shapes"].clone()
            } else {
                state.db.get_shapes(id).unwrap_or(json!({"nodeShapes":[]}))
            };
            let shapes: shacl::Shapes = match serde_json::from_value(raw) {
                Ok(s) => s,
                Err(e) => return err(e.to_string()),
            };
            match state
                .graph_for(id)
                .and_then(|g| shacl::validate(&g, &base, &pfx, &shapes))
            {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_materialize" => {
            let id = pid!(args);
            match state.graph_for(id) {
                Ok(g) => match reason::materialize(&g) {
                    Ok(rep) => {
                        let _ = state.persist(id, &g);
                        jout(rep)
                    }
                    Err(e) => err(e.to_string()),
                },
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_resolve_candidates" => {
            let id = pid!(args);
            let (base, pfx) = match state.ctx(id) {
                Ok(v) => v,
                Err(e) => return err(e.to_string()),
            };
            let class = args["class"].as_str().unwrap_or("");
            let lp = args["labelProp"].as_str().unwrap_or("rdfs:label");
            let th = args["threshold"].as_f64().unwrap_or(0.9);
            match state
                .graph_for(id)
                .and_then(|g| resolve::candidates(&g, &base, &pfx, class, lp, th))
            {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_list_batches" => {
            let id = pid!(args);
            match state.graph_for(id).and_then(|g| prov::list_batches(&g)) {
                Ok(v) => jout(v),
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_drop_batch" => {
            let id = pid!(args);
            let iri = args["iri"].as_str().unwrap_or("");
            match state.graph_for(id) {
                Ok(g) => match prov::drop_batch(&g, iri) {
                    Ok(()) => {
                        let _ = state.persist(id, &g);
                        jout(json!({ "ok": true }))
                    }
                    Err(e) => err(e.to_string()),
                },
                Err(e) => err(e.to_string()),
            }
        }
        "ontology_extract" => {
            let id = pid!(args);
            run_extract(state, id, args).await
        }
        _ => err(format!("Unknown tool: {name}")),
    }
}

async fn run_tbox(state: &Arc<AppState>, id: i64, args: &Value, is_class: bool) -> Value {
    let (base, pfx) = match state.ctx(id) {
        Ok(v) => v,
        Err(e) => return err(e.to_string()),
    };
    let g = match state.graph_for(id) {
        Ok(g) => g,
        Err(e) => return err(e.to_string()),
    };
    let res = if is_class {
        serde_json::from_value::<tbox::ClassDef>(args.clone())
            .map_err(|e| e.to_string())
            .and_then(|d| tbox::add_class(&g, &base, &pfx, &d).map_err(|e| e.to_string()))
    } else {
        serde_json::from_value::<tbox::PropertyDef>(args.clone())
            .map_err(|e| e.to_string())
            .and_then(|d| tbox::add_property(&g, &base, &pfx, &d).map_err(|e| e.to_string()))
    };
    match res {
        Ok(iri) => {
            let _ = state.persist(id, &g);
            jout(json!({ "iri": iri }))
        }
        Err(e) => err(e),
    }
}

async fn run_lift(state: &Arc<AppState>, id: i64, args: &Value, write: bool) -> Value {
    let (base, _pfx) = match state.ctx(id) {
        Ok(v) => v,
        Err(e) => return err(e.to_string()),
    };
    let raw = if args["mapping"].is_object() {
        args["mapping"].clone()
    } else {
        state.db.get_mapping(id).unwrap_or(json!({}))
    };
    let m: mapping::Mapping = match serde_json::from_value(raw) {
        Ok(m) => m,
        Err(e) => return err(format!("invalid mapping: {e}")),
    };
    // Resolve sources.
    let mut sources: HashMap<String, prof::Table> = HashMap::new();
    for tm in &m.triples_maps {
        if sources.contains_key(&tm.source) {
            continue;
        }
        match state.db.source_by_name(id, &tm.source) {
            Ok(Some((kind, content))) => match prof::parse(&kind, &content) {
                Ok(t) => {
                    sources.insert(tm.source.clone(), t);
                }
                Err(e) => return err(e.to_string()),
            },
            _ => return err(format!("source '{}' not uploaded", tm.source)),
        }
    }
    let g = match state.graph_for(id) {
        Ok(g) => g,
        Err(e) => return err(e.to_string()),
    };
    if write {
        let ts = now();
        let label = m
            .triples_maps
            .first()
            .map(|t| t.source.clone())
            .unwrap_or_else(|| "import".into());
        let batch = prov::batch_iri(ts, &label);
        match mapping::lift(&g, &m, &sources, &base, &batch) {
            Ok(rep) => {
                let _ = prov::record_batch(&g, &batch, &label, &label, "lift", rep.triples, ts);
                let _ = state.persist(id, &g);
                jout(
                    json!({ "batch": batch, "triples": rep.triples, "subjects": rep.subjects, "skippedRows": rep.skipped_rows, "totalTriples": g.len() }),
                )
            }
            Err(e) => err(e.to_string()),
        }
    } else {
        match mapping::preview(&m, &sources, &base, 25) {
            Ok(rep) => jout(json!({
                "triples": rep.triples, "subjects": rep.subjects, "skippedRows": rep.skipped_rows,
                "samples": rep.samples.iter().map(|(a,b,c)| json!([a,b,c])).collect::<Vec<_>>(),
            })),
            Err(e) => err(e.to_string()),
        }
    }
}

fn run_competency(state: &Arc<AppState>, id: i64) -> Value {
    let g = match state.graph_for(id) {
        Ok(g) => g,
        Err(e) => return err(e.to_string()),
    };
    let pfx = state.ctx(id).map(|(_, p)| p).unwrap_or_default();
    let cqs = match state.db.list_cq(id) {
        Ok(v) => v,
        Err(e) => return err(e.to_string()),
    };
    let mut results = Vec::new();
    let mut passed = 0;
    for cq in &cqs {
        if cq.sparql.trim().is_empty() {
            results.push(json!({ "question": cq.question, "pass": false, "error": "no SPARQL" }));
            continue;
        }
        match g.query_json(&crate::vocab::ensure_prefixes(&cq.sparql, &pfx)) {
            Ok(res) => {
                let count = res["rows"].as_array().map(|a| a.len()).unwrap_or(0);
                let pass = match cq.expect.as_str() {
                    "empty" => count == 0,
                    "boolean" => res["boolean"].as_bool().unwrap_or(false),
                    _ => count > 0 || res["boolean"].as_bool().unwrap_or(false),
                };
                if pass {
                    passed += 1;
                }
                results.push(json!({ "question": cq.question, "pass": pass, "count": count }));
            }
            Err(e) => results
                .push(json!({ "question": cq.question, "pass": false, "error": e.to_string() })),
        }
    }
    jout(json!({ "total": cqs.len(), "passed": passed, "results": results }))
}

async fn run_extract(state: &Arc<AppState>, id: i64, args: &Value) -> Value {
    let (base, pfx) = match state.ctx(id) {
        Ok(v) => v,
        Err(e) => return err(e.to_string()),
    };
    let txt = args["text"].as_str().unwrap_or("");
    if txt.trim().is_empty() {
        return err("text is required".into());
    }
    let g = match state.graph_for(id) {
        Ok(g) => g,
        Err(e) => return err(e.to_string()),
    };
    let tb = tbox::read(&g).unwrap_or(json!({}));
    let max_chunks = args["maxChunks"].as_u64().unwrap_or(12) as usize;
    let (triples, model, chunks, errors) =
        match llm::extract_triples_chunked(txt, &tb, max_chunks).await {
            Ok(v) => v,
            Err(e) => return err(e),
        };
    let label = args["label"].as_str().unwrap_or("text extraction");
    match crate::auto::insert_extracted(state, id, &g, label, &triples, &base, &pfx) {
        Ok(inserted) => jout(
            json!({ "inserted": inserted, "model": model, "chunks": chunks, "errors": errors }),
        ),
        Err(e) => err(e),
    }
}
